# Generated by Django 5.2.8 on 2025-11-28 05:54

import multiselectfield.db.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0003_lesson_content_en_lesson_content_ru_lesson_title_en_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='level',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=150),
        ),
    ]
