# Generated by Django 5.2.8 on 2025-11-29 10:18

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('course_app', '0007_alter_assignment_course_alter_course_created_by_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='assignment',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments_student', to=settings.AUTH_USER_MODEL),
        ),
    ]
